version: '3'
services:
  exec-label-maker:
    image: developmentseed/docker-label-maker:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: >
      /bin/bash -c "
      echo Starting ...;
      ./start.sh"